//////////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the University of Illinois/NCSA Open Source License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2026 QMCPACK developers.
//////////////////////////////////////////////////////////////////////////////////////

/** @file test_psiformer_value_executor.cpp
 * @brief Direct value-only PsiFormer kernel tests against native and JAX oracles.
 */

#include <catch2/catch_test_macros.hpp>
#include "Utilities/for_testing/Catch2Approx.h"

#define PSIFORMER_LIBRARY
#include "QMCWaveFunctions/PsiFormer/PsiFormerNative.h"
#include "QMCWaveFunctions/PsiFormer/PsiFormerValueExecutor.h"
#include "psiformer_test_utils.h"

#include <atomic>
#include <cstdlib>
#include <memory>
#include <new>
#include <string>

namespace
{
std::atomic<bool> count_allocations{false};
std::atomic<std::size_t> allocation_count{0};
}

/// Count ordinary heap allocations only while a direct-evaluation audit is active.
void* operator new(std::size_t bytes)
{
  if (count_allocations.load(std::memory_order_relaxed))
    allocation_count.fetch_add(1, std::memory_order_relaxed);
  if (void* storage = std::malloc(bytes))
    return storage;
  throw std::bad_alloc();
}

/// Apply the same scoped accounting to array allocations.
void* operator new[](std::size_t bytes)
{
  return ::operator new(bytes);
}

/// Release storage allocated by the test-local ordinary new override.
void operator delete(void* storage) noexcept { std::free(storage); }

/// Release storage allocated by the test-local array new override.
void operator delete[](void* storage) noexcept { std::free(storage); }

/// Support sized deallocation selected by optimized builds.
void operator delete(void* storage, std::size_t) noexcept { std::free(storage); }

/// Support sized array deallocation selected by optimized builds.
void operator delete[](void* storage, std::size_t) noexcept { std::free(storage); }

namespace
{
using namespace qmcplusplus::testing::psiformer;

/** Validate one external-data-free fixture against the graph oracle and compact
 * values independently generated by DeepQMC/JAX. */
void validateDirectValue(const std::string& system,
                         double jax_sign,
                         double jax_logabs,
                         double jax_value)
{
  GeneratedFiles files = generateFiles(system);
  pf::PsiFormer model(files.parameters, files.configuration);
  const qmcplusplus::psiformer::ModelShape shape{
      model.cfg.nup, model.cfg.ndown, model.cfg.nuclei.shape[0], model.ndet, model.dim, model.heads, 4};
  const auto plan = qmcplusplus::psiformer::PsiFormerExecutionPlan::fromParameters(model.p, shape);
  pf::DirectValueExecutor executor(model, plan);
  std::unique_ptr<pf::DirectValueWorkspace> workspace = executor.makeWorkspace();
  const pf::Tensor electrons = model.cfg.configuration(0);
  workspace->setPositions(pf::GeometryPositionView::interleaved(electrons.x.data(), model.ne));

  pf::EvaluationRequest request;
  request.spatial_derivatives    = pf::SpatialDerivativeRequest::NONE;
  request.parameter_derivatives  = pf::ParameterDerivativeRequest::NONE;
  request.validation_hamiltonian = pf::ValidationHamiltonianRequest::NONE;
  const pf::Result oracle            = model.evaluate(electrons, request);
  const pf::DirectValueResult direct = executor.evaluate(*workspace);

  CHECK(direct.sign == oracle.sign);
  CHECK(direct.logabs == Catch::Approx(oracle.logabs).epsilon(2e-11).margin(2e-11));
  CHECK(direct.value == Catch::Approx(oracle.value).epsilon(2e-10).margin(1e-24));
  CHECK(direct.sign == jax_sign);
  CHECK(direct.logabs == Catch::Approx(jax_logabs).epsilon(2e-10).margin(2e-10));
  CHECK(direct.value == Catch::Approx(jax_value).epsilon(2e-9).margin(1e-24));
  CHECK(direct.parameter_version == model.p.version());
  CHECK(workspace->observedParameterVersion() == model.p.version());

  // Descriptors contain offsets rather than value pointers and remain correct
  // after a normal optimizer update changes the backing vector and its version.
  model.p.set_flat_value(127, model.p.flat_values()[127] + 1.0e-3);
  const pf::DirectValueResult changed_direct = executor.evaluate(*workspace);
  const pf::Result changed_oracle             = model.evaluate(electrons, request);
  CHECK(changed_direct.sign == changed_oracle.sign);
  CHECK(changed_direct.logabs == Catch::Approx(changed_oracle.logabs).epsilon(2e-11).margin(2e-11));
  CHECK(changed_direct.parameter_version == model.p.version());

  // A warmed executor must reuse every geometry and activation buffer.  Keep
  // Catch assertions outside the measurement window because they may allocate.
  volatile double allocation_sink = changed_direct.logabs;
  allocation_count.store(0, std::memory_order_relaxed);
  count_allocations.store(true, std::memory_order_relaxed);
  for (int repetition = 0; repetition < 10; ++repetition)
    allocation_sink += executor.evaluate(*workspace).logabs;
  count_allocations.store(false, std::memory_order_relaxed);
  CHECK(allocation_count.load(std::memory_order_relaxed) == 0);
  CHECK(std::isfinite(allocation_sink));
}

} // namespace

TEST_CASE("PsiFormer direct value executor matches native and JAX LiH",
          "[wavefunction][psiformer]")
{
  validateDirectValue("lih", -1.0, -23.077667467509848, -9.495030490017006e-11);
}

TEST_CASE("PsiFormer direct value executor matches native and JAX separated LiH pair",
          "[wavefunction][psiformer]")
{
  validateDirectValue("lih_pair", -1.0, -35.19505925284793, -5.187761194606605e-16);
}

TEST_CASE("PsiFormer direct value supports canonical pseudo-LiH without same-spin alpha",
          "[wavefunction][psiformer][ecp]")
{
  GeneratedFiles files = generateFiles("lih_pp");
  pf::PsiFormer model(files.parameters, files.configuration);
  const qmcplusplus::psiformer::ModelShape shape{
      model.cfg.nup, model.cfg.ndown, model.cfg.nuclei.shape[0], model.ndet, model.dim,
      model.heads, model.blocks};
  const auto plan = qmcplusplus::psiformer::PsiFormerExecutionPlan::fromParameters(model.p, shape);
  CHECK_FALSE(plan.hasParameter(qmcplusplus::psiformer::ParameterRole::CUSP_SAME_ALPHA));

  pf::DirectValueExecutor executor(model, plan);
  std::unique_ptr<pf::DirectValueWorkspace> workspace = executor.makeWorkspace();
  const pf::Tensor electrons = model.cfg.configuration(0);
  workspace->setPositions(pf::GeometryPositionView::interleaved(electrons.x.data(), model.ne));

  pf::EvaluationRequest request;
  request.spatial_derivatives    = pf::SpatialDerivativeRequest::NONE;
  request.parameter_derivatives  = pf::ParameterDerivativeRequest::NONE;
  request.validation_hamiltonian = pf::ValidationHamiltonianRequest::NONE;
  const pf::Result oracle            = model.evaluate(electrons, request);
  const pf::DirectValueResult direct = executor.evaluate(*workspace);
  CHECK(direct.sign == oracle.sign);
  CHECK(direct.logabs == Catch::Approx(oracle.logabs).epsilon(2e-11).margin(2e-11));
  CHECK(direct.value == Catch::Approx(oracle.value).epsilon(2e-10).margin(1e-24));
}
